### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by Ashishrock9394** [Rocks9394/Sparks_Bakers#2]
Create a login page having a mobile number and pass(Password must have 8 digits/letters). mobile number having id mobile and password having id password

**Comment by PST09** [comment]
hii

**Comment by Yadav123Rahul** [comment]
what's your problem

**Comment by PST09** [comment]
hello rahul

**Comment by Ashishrock9394** [comment]
ref:- https://thumbs.dreamstime.com/z/login-page-purple-gradient-sign-form-modern-abstract-background-professional-web-design-violet-color-138416145.jpg
